version: "3.7"
services:
  php7:
    build: .docker/php
    volumes:
      - ~/.composer:/root/.composer
      - ./:/app
      - .docker/php/config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - XDEBUG_CONFIG
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - .docker/mariadb/config:/etc/mysql/conf.d
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - TZ